# Generated by Django 5.2.7 on 2025-11-03 21:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_discount_amount_order_shipping_cost_coupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text='Nom public de votre boutique (ex: « Maison Éternelle »)', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo carré 400×400px recommandé', upload_to='vendors/logos/')),
                ('banner', models.ImageField(blank=True, help_text='Bannière 1920×600px', upload_to='vendors/banners/')),
                ('description', models.TextField(blank=True, help_text='Présentez votre histoire, votre savoir-faire…', max_length=1000)),
                ('short_bio', models.CharField(blank=True, help_text='Phrase d’accroche (meta description)', max_length=160)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Pourcentage prélevé par LuxuryZone (ex: 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_approved', models.BooleanField(default=False, help_text='Cochez pour activer la boutique')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boutique Vendeur',
                'verbose_name_plural': 'Boutiques Vendeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_created_3ffca3_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_status_63c2c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_paid_ff8e98_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Catégories spécifiques', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Produits spécifiques', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='single_use_per_user',
            field=models.BooleanField(default=False, help_text='Limité à une utilisation par utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='shop_order_created_cbf7b4_idx'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.vendor'),
        ),
    ]
